### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TeaqariaWTF** [Davilarek/download-navi#2]
Can the program automatically download multiple download links in a txt file?

Example:file.txt
download.link1
Download.link2
Download.link3

The program should take them from the txt file and start the download process itself.

**Comment by TeaqariaWTF** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
	at com.tachibana.downloader.ui.main.MainActivity.lambda$onActivityResult$13$com-tachibana-downloader-ui-main-MainActivity(MainActivity.java:514)
	at com.tachibana.downloader.ui.main.MainActivity$$ExternalSyntheticLambda8.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by TeaqariaWTF** [comment]
The import feature is unfortunately not working

@Davilarek

**Comment by Davilarek** [comment]
are you using output of export feature? or self made file?

**Comment by TeaqariaWTF** [comment]
> dışa aktarma özelliğinin çıktısını mı kullanıyorsunuz? veya kendi kendine yapılan dosya?

import feature doesn't get download links from file

**Comment by Davilarek** [comment]
can you send file content? also, may be fixed in c2aff28

**Comment by Davilarek** [comment]
if not, please make new issue with sample url list.

**Comment by TeaqariaWTF** [comment]
![Screenshot_20221221-001628_Download Navi](https://user-images.githubusercontent.com/90970076/208768556-d2fc066a-159b-4b11-8c36-6ad234b42bd2.png)

It's working fine now with the latest update.
@Davilarek
